sudo: required

services: docker

before_install:
  - docker-compose up --build -db

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails test
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
